export const CARD_ACTION_TYPES = {
  SET_CARD_ITEMS: 'card/SET_CARD_ITEMS',
  SET_IS_CARD_OPEN: 'card/SET_IS_CARD_OPEN',
  SET_CARD_COUNT: 'card/SET_CARD_COUNT',
  SET_CARD_TOTAL: 'card/SET_CARD_TOTAL',
};
